Repository stone-payments/emerald-components-android, pull requests merged in 2018-10, with the labels that each got.

#36 refacetor/issue 33
  app/build.gradle
  app/src/androidTest/java/br/com/stone/emeraldcomponentsandroid/BaseScreenshotTest.kt
  app/src/androidTest/java/br/com/stone/emeraldcomponentsandroid/ShotTestRunner.kt
  app/src/androidTest/java/br/com/stone/emeraldcomponentsandroid/activities/DateActivityTest.kt
  app/src/androidTest/java/br/com/stone/emeraldcomponentsandroid/activities/SpinnerTestBase.kt
  app/src/main/AndroidManifest.xml
  build.gradle
Labels: develop

#37 :rocket: release/v0.2.3
  CHANGELOG.md
  emeraldcomponents/build.gradle
Labels: develop, release

#38 :rocket: release/v0.2.3
  CHANGELOG.md
  app/build.gradle
  app/src/androidTest/java/br/com/stone/emeraldcomponentsandroid/BaseScreenshotTest.kt
  app/src/androidTest/java/br/com/stone/emeraldcomponentsandroid/ShotTestRunner.kt
  app/src/androidTest/java/br/com/stone/emeraldcomponentsandroid/activities/CalendarActivityTest.kt
  app/src/androidTest/java/br/com/stone/emeraldcomponentsandroid/activities/DateActivityTest.kt
  app/src/androidTest/java/br/com/stone/emeraldcomponentsandroid/activities/InputActivityTest.kt
  app/src/androidTest/java/br/com/stone/emeraldcomponentsandroid/activities/SpinnerTestBase.kt
  app/src/main/AndroidManifest.xml
  build.gradle
  emeraldcomponents/build.gradle
Labels: release

#41 Add emerald colors
  CHANGELOG.md
  emeraldcomponents/src/main/res/values/colors.xml
  emeraldcomponents/src/main/res/values/public.xml
Labels: enhancement
