Repository stone-payments/emerald-components-android, pull requests merged in 2019-12, with the labels that each got.

#144 Release/v1.7.0
  CHANGELOG.md
  emeraldcomponents/build.gradle
Labels: develop

#143 Release/v1.7.0
  CHANGELOG.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/br/com/stone/emeraldcomponentsandroid/MainActivity.kt
  app/src/main/java/br/com/stone/emeraldcomponentsandroid/activities/CounterActivity.kt
  app/src/main/res/layout/activity_counter.xml
  app/src/main/res/layout/activity_input.xml
  app/src/main/res/values/styles.xml
  emeraldcomponents/build.gradle
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/counter/EmeraldCounter.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/input/EmeraldBaseEditText.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/input/EmeraldEditText.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/input/EmeraldMaskedEditText.kt
  emeraldcomponents/src/main/res/drawable/button_enabled_selector.xml
  emeraldcomponents/src/main/res/drawable/rounded_corner.xml
  emeraldcomponents/src/main/res/layout/widget_counter.xml
  emeraldcomponents/src/main/res/values/attrs.xml
  emeraldcomponents/src/main/res/values/strings.xml
  emeraldcomponents/src/main/res/values/styles.xml
  emeraldcomponents/src/test/java/br/com/stone/emeraldcomponents/basics/counter/EmeraldCounterTest.kt
  emeraldcomponents/src/test/java/br/com/stone/emeraldcomponents/basics/input/EmeraldMaskedEditTextTest.kt
Labels: master

#148 release/v1.8.0
  CHANGELOG.md
  emeraldcomponents/build.gradle
Labels: develop, release

#147 Release/v1.8.0
  CHANGELOG.md
  app/src/main/java/br/com/stone/emeraldcomponentsandroid/activities/SpinnerActivity.kt
  app/src/main/res/layout/activity_spinner.xml
  app/src/main/res/layout/spinner_text.xml
  emeraldcomponents/build.gradle
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/counter/EmeraldCounter.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/spinner/EmeraldSpinner.kt
  emeraldcomponents/src/test/java/br/com/stone/emeraldcomponents/basics/counter/EmeraldCounterTest.kt
  emeraldcomponents/src/test/java/br/com/stone/emeraldcomponents/basics/input/EmeraldMaskedEditTextTest.kt
Labels: master, release
