Repository stone-payments/emerald-components-android, pull requests merged in 2020-06, with the labels that each got.

#175 Release/v1.12.0
  CHANGELOG.md
  emeraldcomponents/build.gradle
Labels: develop, release

#174 Release/v1.12.0
  CHANGELOG.md
  app/src/main/res/layout/activity_label.xml
  app/src/main/res/layout/icon_label.xml
  app/src/main/res/layout/margin_label.xml
  app/src/main/res/layout/shape_label.xml
  app/src/main/res/values/strings.xml
  emeraldcomponents/build.gradle
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/label/EmeraldLabel.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/label/EmeraldLabelIconPosition.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/label/EmeraldLabelMargin.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/label/EmeraldLabelShape.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/label/LabelMarginHandler.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/label/LabelShapeHandler.kt
  emeraldcomponents/src/main/res/drawable/label_border_squared.xml
  emeraldcomponents/src/main/res/layout/widget_emerald_label.xml
  emeraldcomponents/src/main/res/values/attrs.xml
  emeraldcomponents/src/main/res/values/dimens.xml
  emeraldcomponents/src/test/java/br/com/stone/emeraldcomponents/basics/label/EmeraldLabelMarginTest.kt
  emeraldcomponents/src/test/java/br/com/stone/emeraldcomponents/basics/label/EmeraldLabelShapeTest.kt
  emeraldcomponents/src/test/java/br/com/stone/emeraldcomponents/basics/label/EmeraldLabelTest.kt
  emeraldcomponents/src/test/java/br/com/stone/emeraldcomponents/basics/seekbar/EmeraldScoreSeekBarTest.kt
Labels: master, release

#176 Release/1.13.0
  CHANGELOG.md
  emeraldcomponents/build.gradle
Labels: develop, release

#177 Release/1.13.0
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/br/com/stone/emeraldcomponentsandroid/MainActivity.kt
  app/src/main/java/br/com/stone/emeraldcomponentsandroid/activities/PinViewActivity.kt
  app/src/main/res/layout/activity_pin_view.xml
  emeraldcomponents/build.gradle
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/label/EmeraldHideableLabel.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/pinview/EmeraldPinCodeView.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/pinview/EmeraldPinItemView.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/pinview/PinCodeState.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/extension/Dip.kt
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/extension/String.kt
  emeraldcomponents/src/main/res/drawable/stroke_box_gray.xml
  emeraldcomponents/src/main/res/drawable/stroke_box_red.xml
  emeraldcomponents/src/main/res/layout/emerald_pin_item.xml
  emeraldcomponents/src/main/res/values/attrs.xml
  emeraldcomponents/src/main/res/values/colors.xml
  emeraldcomponents/src/main/res/values/dimens.xml
  emeraldcomponents/src/main/res/values/styles.xml
  emeraldcomponents/src/test/java/br/com/stone/emeraldcomponents/basics/pincode/EmeraldPinCodeViewTest.kt
  emeraldcomponents/src/test/java/br/com/stone/emeraldcomponents/basics/seekbar/EmeraldScoreSeekBarTest.kt
Labels: master, release

#180 Feature/1.14.0
  CHANGELOG.md
  emeraldcomponents/build.gradle
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/label/EmeraldLabel.kt
  emeraldcomponents/src/test/java/br/com/stone/emeraldcomponents/basics/label/EmeraldLabelTest.kt
Labels: master, release

#181 Feature/1.14.0
  CHANGELOG.md
  emeraldcomponents/build.gradle
Labels: develop, release

#183 Adds a init method to EmeraldPinCodeView.kt
  CHANGELOG.md
  app/src/main/java/br/com/stone/emeraldcomponentsandroid/activities/PinViewActivity.kt
  app/src/main/res/layout/activity_pin_view.xml
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/pinview/EmeraldPinCodeView.kt
  emeraldcomponents/src/main/res/values/attrs.xml
  emeraldcomponents/src/test/java/br/com/stone/emeraldcomponents/basics/pincode/EmeraldPinCodeViewTest.kt
Labels: enhancement

#186 Release/1.14.1
  CHANGELOG.md
  emeraldcomponents/build.gradle
Labels: develop, release

#185 Release/1.14.1
  CHANGELOG.md
  app/src/main/java/br/com/stone/emeraldcomponentsandroid/activities/PinViewActivity.kt
  app/src/main/res/layout/activity_pin_view.xml
  build.gradle
  emeraldcomponents/build.gradle
  emeraldcomponents/src/main/java/br/com/stone/emeraldcomponents/basic/pinview/EmeraldPinCodeView.kt
  emeraldcomponents/src/main/res/values/attrs.xml
  emeraldcomponents/src/test/java/br/com/stone/emeraldcomponents/basics/pincode/EmeraldPinCodeViewTest.kt
Labels: master, release
